project:
  type: website
  output-dir: docs

website:
  title: "MSDS-534"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - getting-started/getting-started.ipynb
      - lec-1/lecture-1.ipynb
      - lec-2/lecture-2.ipynb
      - lec-3/lecture-3.ipynb
      - section: lec-4/lecture-4.ipynb
        contents:
        - lec-4/gpt.qmd
      - lec-5/lecture-5.ipynb
      - lec-6/lecture-6.ipynb
      - lec-7/lecture-7.ipynb
      - section: lec-8/lecture-8-classification.ipynb   
        contents:
        - lec-8/lecture-8-caveat.ipynb      
      - lec-9/lecture-9.ipynb   
      - lec-10/lecture-10.ipynb   
  repo-url: https://github.com/moran-teaching/msds534-website   
  repo-branch: main                                             
  repo-actions: [source] 
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



